package siet.modelo;
// Generated 25/05/2010 10:15:41 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {
    public static String ACCION_LOGIN = "LOGIN";
    public static String ACCION_LOGOFF = "LOGOFF";
    public static String ACCION_CREACION = "CREACION";
    public static String ACCION_MODIFICACION = "MODIFICACION";
    public static String ACCION_ELIMINACION = "ELIMINACION";

    public static String ENTIDAD_PROYECTO = "Proyecto";
    public static String ENTIDAD_EMPLEADO = "Empleado";
    public static String ENTIDAD_CLIENTE = "Cliente";
    public static String ENTIDAD_DOCUMENTACION = "Documentacion";
    public static String ENTIDAD_TIPO_VIVIENDA = "TipoVivienda";

    private Long id=-1L;
    private Date fecha = new Date();
    private Empleado empleado;
    private Cliente cliente;
    private String accion;
    private String mensaje;
    private String entidad;

    public Auditoria() {
    }

    public Auditoria(Cliente cliente, String accion, String mensaje, String entidad) {
        this.cliente = cliente;
        this.accion = accion;
        this.mensaje = mensaje;
        this.entidad = entidad;
    }

    public Auditoria(Empleado empleado, String accion, String mensaje, String entidad) {
        this.empleado = empleado;
        this.accion = accion;
        this.mensaje = mensaje;
        this.entidad = entidad;
    }


    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the fecha
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * @param fecha the fecha to set
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * @return the empleado
     */
    public Empleado getEmpleado() {
        return empleado;
    }

    /**
     * @param empleado the empleado to set
     */
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    /**
     * @return the cliente
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    /**
     * @return the accion
     */
    public String getAccion() {
        return accion;
    }

    /**
     * @param accion the accion to set
     */
    public void setAccion(String accion) {
        this.accion = accion;
    }

    /**
     * @return the mensaje
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * @param mensaje the mensaje to set
     */
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    /**
     * @return the entidad
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * @param entidad the entidad to set
     */
    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }

    @Override
    public String toString() {
        return "id: " + id;
    }


}


