package siet.modelo;
// Generated 25/05/2010 10:15:41 PM by Hibernate Tools 3.2.1.GA



/**
 * Cliente generated by hbm2java
 */
public class Proyecto extends Object implements java.io.Serializable {

    private Long id = -1L;
   
    private String nombre;
    private String descripcion;
    private int maximoClientes;
    private boolean estado;
    private Empleado jefe;

    public Proyecto() {
    }

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param descripcion the descripcion to set
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return the maximoClientes
     */
    public int getMaximoClientes() {
        return maximoClientes;
    }

    /**
     * @param maximoClientes the maximoClientes to set
     */
    public void setMaximoClientes(int maximoClientes) {
        this.maximoClientes = maximoClientes;
    }

    /**
     * @return the estado
     */
    public boolean isEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    /**
     * @return the jefe
     */
    public Empleado getJefe() {
        return jefe;
    }

    /**
     * @param jefe the jefe to set
     */
    public void setJefe(Empleado jefe) {
        this.jefe = jefe;
    }

    



}


